[package]
name = "json-mutex-db"
version = "0.0.1"
edition = "2024"
authors = [ "Georgii Plotnikov<georgii@inferara.com>" ]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12"
